import './globals.css';
import type { Metadata } from 'next';
import { Dancing_Script } from 'next/font/google';

const dancingScript = Dancing_Script({
  variable: '--font-main',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={dancingScript.variable}>
      <body>{children}</body>
    </html>
  );
}
